"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card"
import { Input } from "@/shared/components/ui/input"
import { Label } from "@/shared/components/ui/label"
import { Tabs, TabsList, TabsTrigger } from "@/shared/components/ui/tabs"
import { Clock, DollarSign, Sparkles, Calculator } from "lucide-react"
import { Badge } from "@/shared/components/ui/badge"

export default function PricingPage() {
  const [inputTokens, setInputTokens] = useState<number>(1000)
  const [outputTokens, setOutputTokens] = useState<number>(500)
  const [isDiscountTime, setIsDiscountTime] = useState<boolean>(false)

  // Calculate costs
  const inputCost = (inputTokens / 1000000) * 2 // $2 per million input tokens
  const outputCost = (outputTokens / 1000000) * 4 // $4 per million output tokens
  const totalCost = inputCost + outputCost
  const discountedCost = totalCost * 0.25 // 75% discount
  const finalCost = isDiscountTime ? discountedCost : totalCost

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-red-600">Pricing</h1>
        <p className="text-zinc-900 dark:text-white">Transparent pricing for Swarms API usage</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="border-red-500/50 hover:border-red-600 hover:shadow-lg transition-all duration-200">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <DollarSign className="h-5 w-5 text-red-500" />
              Token Pricing
            </CardTitle>
            <CardDescription>Our simple and transparent pricing model</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-1 gap-4">
              <div className="bg-zinc-100 dark:bg-zinc-900 p-4 rounded-lg border border-zinc-200 dark:border-zinc-800">
                <div className="flex justify-between items-center mb-2">
                  <h3 className="font-medium">Input Tokens</h3>
                  <Badge variant="outline" className="border-red-500 text-red-500">
                    $2.00 / million
                  </Badge>
                </div>
                <p className="text-sm text-zinc-500 dark:text-zinc-400">
                  Tokens used in prompts, instructions, and other inputs to the API
                </p>
              </div>

              <div className="bg-zinc-100 dark:bg-zinc-900 p-4 rounded-lg border border-zinc-200 dark:border-zinc-800">
                <div className="flex justify-between items-center mb-2">
                  <h3 className="font-medium">Output Tokens</h3>
                  <Badge variant="outline" className="border-red-500 text-red-500">
                    $4.00 / million
                  </Badge>
                </div>
                <p className="text-sm text-zinc-500 dark:text-zinc-400">
                  Tokens generated by the model in response to your inputs
                </p>
              </div>
            </div>

            <div className="bg-red-50 dark:bg-red-950/20 p-4 rounded-lg border border-red-200 dark:border-red-900/50">
              <div className="flex items-start gap-3">
                <Clock className="h-5 w-5 text-red-500 mt-0.5" />
                <div>
                  <h3 className="font-medium text-red-700 dark:text-red-400">Off-Peak Discount</h3>
                  <p className="text-sm text-red-600 dark:text-red-300 mt-1">
                    Enjoy a <span className="font-bold">75% discount</span> on all token pricing from 8:00 PM to 6:00 AM
                    PST.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-red-500/50 hover:border-red-600 hover:shadow-lg transition-all duration-200">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calculator className="h-5 w-5 text-red-500" />
              Cost Calculator
            </CardTitle>
            <CardDescription>Estimate your costs based on token usage</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="input-tokens">Input Tokens</Label>
                <Input
                  id="input-tokens"
                  type="number"
                  min="0"
                  value={inputTokens}
                  onChange={(e) => setInputTokens(Number.parseInt(e.target.value) || 0)}
                  className="dark:border-zinc-700"
                />
                <p className="text-xs text-zinc-500 dark:text-zinc-400">Estimated cost: ${inputCost.toFixed(6)}</p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="output-tokens">Output Tokens</Label>
                <Input
                  id="output-tokens"
                  type="number"
                  min="0"
                  value={outputTokens}
                  onChange={(e) => setOutputTokens(Number.parseInt(e.target.value) || 0)}
                  className="dark:border-zinc-700"
                />
                <p className="text-xs text-zinc-500 dark:text-zinc-400">Estimated cost: ${outputCost.toFixed(6)}</p>
              </div>

              <div className="pt-2">
                <div className="flex items-center justify-between mb-2">
                  <span>Apply off-peak discount (8PM-6AM PST)</span>
                  <Tabs value={isDiscountTime ? "yes" : "no"} onValueChange={(v) => setIsDiscountTime(v === "yes")}>
                    <TabsList>
                      <TabsTrigger value="no">No</TabsTrigger>
                      <TabsTrigger value="yes">Yes</TabsTrigger>
                    </TabsList>
                  </Tabs>
                </div>
              </div>
            </div>

            <div className="bg-zinc-100 dark:bg-zinc-900 p-4 rounded-lg border border-zinc-200 dark:border-zinc-800">
              <div className="flex justify-between items-center mb-1">
                <h3 className="font-medium">Total Cost</h3>
                <span className="text-lg font-bold">${finalCost.toFixed(6)}</span>
              </div>
              {isDiscountTime && (
                <div className="flex justify-between items-center text-sm">
                  <span className="text-red-500">75% Discount Applied</span>
                  <span className="text-red-500">-${(totalCost - discountedCost).toFixed(6)}</span>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="border-red-500/50 hover:border-red-600 hover:shadow-lg transition-all duration-200">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-red-500" />
            Pricing FAQ
          </CardTitle>
          <CardDescription>Common questions about our pricing model</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <h3 className="font-medium">How are tokens counted?</h3>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                Tokens are pieces of text that models process. A token is approximately 4 characters or 0.75 words in
                English. Both input and output tokens are counted and billed separately.
              </p>
            </div>

            <div className="space-y-2">
              <h3 className="font-medium">What is the off-peak discount?</h3>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                We offer a 75% discount on all token pricing during off-peak hours (8:00 PM to 6:00 AM PST) to encourage
                efficient usage of our infrastructure.
              </p>
            </div>

            <div className="space-y-2">
              <h3 className="font-medium">Are there any additional fees?</h3>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                No, our pricing is transparent with no hidden fees. You only pay for the tokens you use at the rates
                specified above.
              </p>
            </div>

            <div className="space-y-2">
              <h3 className="font-medium">Do you offer volume discounts?</h3>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                Yes, we offer custom pricing for high-volume users. Please contact our sales team for more information
                on enterprise pricing.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

